// Copyright (c) 2026 Pierre G. Boutquin. All rights reserved.
//
//   Licensed under the Apache License, Version 2.0 (the "License").
//   You may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

using System.Text.Json;

namespace Boutquin.Numerics.Tests.Verification;

/// <summary>
/// Base class for cross-language verification tests. Loads JSON vectors
/// generated by the Python <c>tests/Verification/generate_*.py</c> scripts
/// and provides tiered precision helpers.
/// </summary>
public abstract class CrossLanguageVerificationBase
{
    /// <summary>Exact arithmetic — simple ratios, lookup tables.</summary>
    protected const double PrecisionExact = 1e-10;

    /// <summary>Iterative / floating-point heavy — matrix ops, iterative solvers.</summary>
    protected const double PrecisionNumeric = 1e-6;

    /// <summary>Statistical sampling — Monte Carlo envelopes.</summary>
    protected const double PrecisionStatistical = 1e-4;

    private static string? s_vectorsDir;

    /// <summary>
    /// Resolves the JSON vectors directory. Checks the runtime output copy
    /// first, falls back to walking up from the test assembly to
    /// <c>tests/Verification/vectors/</c>.
    /// </summary>
    protected static string GetVectorsDir()
    {
        if (s_vectorsDir != null)
        {
            return s_vectorsDir;
        }

        // Output-tree copy (set up by the csproj's Content Include).
        var outputCopy = Path.Combine(AppContext.BaseDirectory, "Verification", "vectors");
        if (Directory.Exists(outputCopy))
        {
            s_vectorsDir = outputCopy;
            return outputCopy;
        }

        var dir = AppContext.BaseDirectory;
        while (dir != null)
        {
            var candidate = Path.Combine(dir, "tests", "Verification", "vectors");
            if (Directory.Exists(candidate))
            {
                s_vectorsDir = candidate;
                return candidate;
            }

            dir = Directory.GetParent(dir)?.FullName;
        }

        throw new DirectoryNotFoundException(
            "Cannot find tests/Verification/vectors/. Run the Python generators first.");
    }

    protected static JsonDocument LoadVector(string name)
    {
        var path = Path.Combine(GetVectorsDir(), $"{name}.json");
        if (!File.Exists(path))
        {
            throw new FileNotFoundException(
                $"Vector file not found: {path}. Run the Python generator first.",
                path);
        }

        var json = File.ReadAllText(path);
        return JsonDocument.Parse(json);
    }

    protected static double[] GetDoubleArray(JsonElement element)
    {
        return element.EnumerateArray().Select(e => e.GetDouble()).ToArray();
    }

    protected static double[,] GetDouble2D(JsonElement element)
    {
        var rows = element.EnumerateArray().Select(GetDoubleArray).ToArray();
        var n = rows.Length;
        var m = rows.Length == 0 ? 0 : rows[0].Length;
        var result = new double[n, m];
        for (var i = 0; i < n; i++)
        {
            for (var j = 0; j < m; j++)
            {
                result[i, j] = rows[i][j];
            }
        }

        return result;
    }

    protected static decimal[] GetDecimalArray(JsonElement element)
    {
        return element.EnumerateArray().Select(e => (decimal)e.GetDouble()).ToArray();
    }

    protected static decimal[,] GetDecimal2D(JsonElement element)
    {
        var rows = element.EnumerateArray().Select(GetDecimalArray).ToArray();
        var n = rows.Length;
        var m = rows.Length == 0 ? 0 : rows[0].Length;
        var result = new decimal[n, m];
        for (var i = 0; i < n; i++)
        {
            for (var j = 0; j < m; j++)
            {
                result[i, j] = rows[i][j];
            }
        }

        return result;
    }

    protected static void AssertScalarWithin(double actual, double expected, double tolerance, string label = "")
    {
        var diff = Math.Abs(actual - expected);
        Assert.True(diff <= tolerance,
            $"{label}: expected {expected}, got {actual}, diff={diff} > tol={tolerance}");
    }

    protected static void AssertScalarWithin(decimal actual, decimal expected, decimal tolerance, string label = "")
    {
        var diff = Math.Abs(actual - expected);
        Assert.True(diff <= tolerance,
            $"{label}: expected {expected}, got {actual}, diff={diff} > tol={tolerance}");
    }

    protected static void AssertMatrixWithin(double[,] actual, double[,] expected, double tolerance, string label = "")
    {
        Assert.Equal(expected.GetLength(0), actual.GetLength(0));
        Assert.Equal(expected.GetLength(1), actual.GetLength(1));
        for (var i = 0; i < expected.GetLength(0); i++)
        {
            for (var j = 0; j < expected.GetLength(1); j++)
            {
                AssertScalarWithin(actual[i, j], expected[i, j], tolerance, $"{label}[{i},{j}]");
            }
        }
    }

    protected static void AssertMatrixWithin(decimal[,] actual, double[,] expected, decimal tolerance, string label = "")
    {
        Assert.Equal(expected.GetLength(0), actual.GetLength(0));
        Assert.Equal(expected.GetLength(1), actual.GetLength(1));
        for (var i = 0; i < expected.GetLength(0); i++)
        {
            for (var j = 0; j < expected.GetLength(1); j++)
            {
                AssertScalarWithin(actual[i, j], (decimal)expected[i, j], tolerance, $"{label}[{i},{j}]");
            }
        }
    }
}
